# HOW TO IMPORT NUMPY 

In [6]:
import numpy as np

In [7]:
a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape
(1, 6)

(1, 6)

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
type(a)

numpy.ndarray

In [10]:
a.shape 

(6,)

# WHAT IS AN ARRAY

In [11]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [12]:
print(a[0])

[1 2 3 4]


In [13]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
a[1][3]


8

# HOW TO CREATE A BASIC ARRAY

In [15]:
a1 = np.array([1, 2, 3])

In [16]:
a1

array([1, 2, 3])

# ADDING, REMOVING,AND SORTING ELEMENTS 

In [17]:
a # adding and romving 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
a[0][1]=0 # removing 2 to 0

In [19]:
a

array([[ 1,  0,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
a[0][1]=15

In [21]:
a # adding 2 to 15

array([[ 1, 15,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
# sort
arr = np.array([[5, 2, 3, 4, 1, 6, 7, 8, 9, 10,11, 12],[5, 2, 3, 4, 1, 6, 7, 8, 9, 10,11, 12]])

In [23]:
np.sort(arr,axis=1) # You can quickly sort the numbers in ascending order with:


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [24]:
# np.concatenate()

In [25]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [26]:
np.concatenate((a,b),axis=0)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [28]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

# How do you know the shape and size of an array?

In [29]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [30]:
array_example.ndim

3

In [31]:
array_example.size


24

In [32]:
array_example.shape

(3, 2, 4)

# Can you reshape an array?

In [38]:
#If you start with this array:
a=np.arange(6)
print(a)

[0 1 2 3 4 5]


In [39]:
# Using arr.reshape()
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [40]:
b.shape 

(3, 2)

In [41]:
np.reshape(a, newshape=(1, 6), order='C')# C-like index order

array([[0, 1, 2, 3, 4, 5]])

In [42]:
a.shape


(6,)