# HOW TO IMPORT NUMPY 

In [86]:
import numpy as np
import seaborn as sns

import matplotlib.pyplot as plt

In [87]:
a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape
(1, 6)

(1, 6)

In [88]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
type(a)

numpy.ndarray

In [90]:
a.shape 

(6,)

# WHAT IS AN ARRAY

In [91]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [92]:
print(a[0])

[1 2 3 4]


In [93]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [94]:
a[1][3]


8

# HOW TO CREATE A BASIC ARRAY

In [95]:
a1 = np.array([1, 2, 3])

In [96]:
a1

array([1, 2, 3])

# ADDING, REMOVING,AND SORTING ELEMENTS 

In [97]:
a # adding and romving 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [98]:
a[0][1]=0 # removing 2 to 0

In [99]:
a

array([[ 1,  0,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [100]:
a[0][1]=15

In [101]:
a # adding 2 to 15

array([[ 1, 15,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [102]:
# sort
arr = np.array([[5, 2, 3, 4, 1, 6, 7, 8, 9, 10,11, 12],[5, 2, 3, 4, 1, 6, 7, 8, 9, 10,11, 12]])

In [103]:
np.sort(arr,axis=1) # You can quickly sort the numbers in ascending order with:


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [104]:
# np.concatenate()

In [105]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [106]:
np.concatenate((a,b),axis=0)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [107]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [108]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

# How do you know the shape and size of an array?

In [109]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [110]:
array_example.ndim

3

In [111]:
array_example.size


24

In [112]:
array_example.shape

(3, 2, 4)

# Can you reshape an array?

In [113]:
#If you start with this array:
a=np.arange(6)
print(a)

[0 1 2 3 4 5]


In [114]:
# Using arr.reshape()
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [115]:
b.shape 

(3, 2)

In [116]:
np.reshape(a, newshape=(1, 6), order='C')# C-like index order

array([[0, 1, 2, 3, 4, 5]])

In [117]:
a.shape


(6,)

## How to convert a 1D array into a 2D array (how to add a new axis to an array)

Using np.newaxis will increase the dimensions of your array by one dimension when used once. 
This means that a 1D array will become a 2D array, a 2D array will become a 3D array, and so on.

In [118]:
# It is an 1 dimension array 
a = np.array([1, 2, 3, 4, 5, 6])
a.shape



(6,)

In [119]:
# now we covert into 2 dimensional array 
a2 = np.array([1, 2, 3, 4, 5, 6])
a2 = a[np.newaxis, :]
a2.shape


(1, 6)

## Indexing and slicing
    You can index and slice NumPy arrays in the same ways you can slice Python lists.

In [120]:
data = np.array([1, 2, 3])
data[1]

2

In [121]:
data[0:3]

array([1, 2, 3])

In [135]:
data[-2]

2

# How to create an array from existing data
    This section covers slicing and indexing, np.vstack(), np.hstack(), np.hsplit(), .view(), copy()

In [136]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [124]:
# where you want to slice your array.
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [125]:
#You can also stack two existing arrays, both vertically and horizontally. Let’s say you have two arrays, a1 and a2:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [126]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [127]:
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [131]:
# You can split an array into several smaller arrays using hsplit.
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [132]:
# If you wanted to split this array into three equally shaped arrays, you would run:
np.hsplit(x,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [134]:
# If you wanted to split your array after the third and fourth column, you’d run:
np.hsplit(x, (3, 4))


[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]